# Networking - WiFi
install iwlwifi /bin/true
install ath9k /bin/true
install ath10k_pci /bin/true
install ath11k /bin/true
install rtw88 /bin/true
install rtw89 /bin/true
install rtl8xxxu /bin/true
install mt7921e /bin/true
install brcmfmac /bin/true
install cfg80211 /bin/true

# Networking - Ethernet
install e1000 /bin/true
install e1000e /bin/true
install r8169 /bin/true
install igb /bin/true
install igc /bin/true
install ixgbe /bin/true